# Generated by Django 5.1.6 on 2026-02-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyuser_email_alter_companyuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
