# Generated by Django 5.1.6 on 2026-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companyuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_user_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='account_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
